import type { Metadata } from "next";
import NavBar from '../components/NavBar';
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Pragati Chaudhary",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar /> {/* Include the NavBar component here */}
        <main>{children}</main> {/* Ensure children are rendered below the NavBar */}
      </body>
    </html>
  );
}
